export { EufyMegaClient } from './client.js';
export { FileSessionStore } from './session.js';
export { EufyError } from './types.js';
export type { DownloadResult, RecordingDownload, EventStatus, ClientEvents } from './types.js';
export type {
  AuthState,
  AuthAnswer,
  Credentials,
  Device,
  CameraCapabilities,
  CameraMediaCapability,
  DeviceRelationship,
  DiscoveryIssue,
  DiscoveryResult,
  ClientOptions,
  Diagnostic,
  Session,
  SessionStore,
  StationState,
  Snapshot,
  MediaMetadata,
  StreamStop,
  LiveStream,
  LiveStartOptions,
  LiveStartStage,
  LiveStartProgress,
  Recording,
  DetectionEvent,
  EventSession,
} from './types.js';
export { EufyClient } from './eufy-client.js';
export type {
  EufyClientOptions,
  ModuleLifecycle,
  ModuleLifecycleState,
  SecurityModule,
  MowerModule,
  MowerOptions,
  MowerDevice,
  MowerHomeOptions,
  MowerAdapter,
  MowerAdapterContext,
  MowerSession,
  MowerSessionStore,
  MowerLocalSessionOptions,
  MowerLocalSession,
  MowerLocalSessionEnd,
  MowerCommandOptions,
  MowerCommandKind,
  MowerCommandRequest,
  MowerCommandProgress,
  MowerCommandWrite,
  MowerCommandStage,
  MowerCommandEnd,
  MowerCommandOutcome,
  MowerSettingsOptions,
  MowerSettingName,
  MowerSettingValue,
  MowerSettingField,
  MowerSettings,
  MowerSettingsDecodeOptions,
  MowerSettingRequest,
  MowerSettingWrite,
  MowerSettingStage,
  MowerSettingEnd,
  MowerSettingOutcome,
  MowerMowSpeed,
  MowerBladeSpeed,
  MowerDirectionMode,
  MowerDirectionConfig,
  MowerWorkParameters,
  MowerWorkParametersFault,
  MowerWorkParametersDecoding,
  MowerWorkParametersReading,
  MowerDpSnapshot,
  MowerDpReport,
  MowerDpValue,
  MowerDpPropertyType,
  MowerDpSchemaEntry,
  MowerTelemetryLevel,
  MowerActivity,
  MowerNetworkKind,
  MowerTelemetryFieldName,
  MowerTelemetryDefinition,
  MowerTelemetryField,
  MowerTelemetryValue,
  MowerTelemetry,
  MowerTelemetryOptions,
  MowerWireField,
  MowerWireFault,
  MowerWirePayload,
} from './modular-types.js';
export { decodeMowerTelemetry } from './mowers/telemetry/decode.js';
export { decodeMowerSettings } from './mowers/local/settings.js';
export { decodeMowerWorkParameters } from './mowers/work-parameters.js';
export { E15_TELEMETRY_DEFINITIONS } from './mowers/telemetry/definitions.js';
export { parseMowerWirePayload } from './mowers/telemetry/wire.js';
export { PortableMapAcquisition } from './mowers/maps/acquisition.js';
export {
  decodeMowerMapFile,
  decodeMowerPathFile,
  decodeMowerPoseFile,
  decodeMowerMapSnapshot,
} from './mowers/maps/geometry.js';
export type {
  MowerMapPoint,
  MowerMapPose,
  MowerMapPolygon,
  MowerMapLine,
  MowerMapEllipse,
  MowerMapZoneShape,
  MowerMapForbiddenZone,
  MowerMapPhysicalForbiddenZone,
  MowerMapRequiredZone,
  MowerMapPassThroughZone,
  MowerMapVirtualWall,
  MowerMapTunnel,
  MowerMapMarker,
  MowerMapTrappedPoint,
  MowerMapMaintenancePoint,
  MowerMapSubRegion,
  MowerMapRegion,
  MowerMapTimestamp,
  MowerMapState,
  MowerMapKind,
  MowerMapIssue,
  MowerMapBounds,
  MowerMap,
  MowerPathKind,
  MowerPathPointKind,
  MowerPathPoint,
  MowerPath,
  MowerMapChannelKind,
  MowerMultiMapKind,
  MowerMultiMap,
  MowerMapChannelMessage,
  MowerMapFileFault,
  MowerMapFileResult,
  MowerMapGeometry,
} from './mowers/maps/geometry.js';
export type { MapWireFault } from './mowers/maps/protobuf.js';
export { MowerPathAccumulator } from './mowers/maps/history.js';
export type {
  MowerMapGeneration,
  MowerPathSegment,
  MowerPathHistory,
  MowerPathMergeInput,
  MowerPathStartReason,
  MowerPathRejection,
  MowerPathMergeResult,
  MowerPathAccumulatorOptions,
} from './mowers/maps/history.js';
export type {
  MapSessionProvisioning,
  MapStreamName,
  MapAcquisitionSnapshot,
  MapAcquisitionDemand,
  MapAcquisitionResult,
  MapAcquisitionEnd,
} from './mowers/maps/types.js';
